//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hospital_ABC.srvMedicoEspecialista {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="srvMedicoEspecialista.IsrvMedicoEspecialista")]
    public interface IsrvMedicoEspecialista {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IsrvMedicoEspecialista/recMedicoEspecialista_PA", ReplyAction="http://tempuri.org/IsrvMedicoEspecialista/recMedicoEspecialista_PAResponse")]
        System.Collections.Generic.List<Entidades.PA_MedicoEspecialista_MostrarDetalle_Result> recMedicoEspecialista_PA();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IsrvMedicoEspecialista/recMedicoEspecialista_PA", ReplyAction="http://tempuri.org/IsrvMedicoEspecialista/recMedicoEspecialista_PAResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.List<Entidades.PA_MedicoEspecialista_MostrarDetalle_Result>> recMedicoEspecialista_PAAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IsrvMedicoEspecialista/recMedicoEspecialistaXID_PA", ReplyAction="http://tempuri.org/IsrvMedicoEspecialista/recMedicoEspecialistaXID_PAResponse")]
        Entidades.PA_MedicoEspecialista_MostrarDetallexid_Result recMedicoEspecialistaXID_PA(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IsrvMedicoEspecialista/recMedicoEspecialistaXID_PA", ReplyAction="http://tempuri.org/IsrvMedicoEspecialista/recMedicoEspecialistaXID_PAResponse")]
        System.Threading.Tasks.Task<Entidades.PA_MedicoEspecialista_MostrarDetallexid_Result> recMedicoEspecialistaXID_PAAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IsrvMedicoEspecialista/insMedicoEspecialista_PA", ReplyAction="http://tempuri.org/IsrvMedicoEspecialista/insMedicoEspecialista_PAResponse")]
        bool insMedicoEspecialista_PA(Entidades.MedicoEspecialista pMedicoEspecialista);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IsrvMedicoEspecialista/insMedicoEspecialista_PA", ReplyAction="http://tempuri.org/IsrvMedicoEspecialista/insMedicoEspecialista_PAResponse")]
        System.Threading.Tasks.Task<bool> insMedicoEspecialista_PAAsync(Entidades.MedicoEspecialista pMedicoEspecialista);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IsrvMedicoEspecialista/modMedicoEspecialista_PA", ReplyAction="http://tempuri.org/IsrvMedicoEspecialista/modMedicoEspecialista_PAResponse")]
        bool modMedicoEspecialista_PA(Entidades.MedicoEspecialista pMedicoEspecialista);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IsrvMedicoEspecialista/modMedicoEspecialista_PA", ReplyAction="http://tempuri.org/IsrvMedicoEspecialista/modMedicoEspecialista_PAResponse")]
        System.Threading.Tasks.Task<bool> modMedicoEspecialista_PAAsync(Entidades.MedicoEspecialista pMedicoEspecialista);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IsrvMedicoEspecialista/delMedicoEspecialista_PA", ReplyAction="http://tempuri.org/IsrvMedicoEspecialista/delMedicoEspecialista_PAResponse")]
        bool delMedicoEspecialista_PA(Entidades.MedicoEspecialista pMedicoEspecialista);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IsrvMedicoEspecialista/delMedicoEspecialista_PA", ReplyAction="http://tempuri.org/IsrvMedicoEspecialista/delMedicoEspecialista_PAResponse")]
        System.Threading.Tasks.Task<bool> delMedicoEspecialista_PAAsync(Entidades.MedicoEspecialista pMedicoEspecialista);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IsrvMedicoEspecialistaChannel : Hospital_ABC.srvMedicoEspecialista.IsrvMedicoEspecialista, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class IsrvMedicoEspecialistaClient : System.ServiceModel.ClientBase<Hospital_ABC.srvMedicoEspecialista.IsrvMedicoEspecialista>, Hospital_ABC.srvMedicoEspecialista.IsrvMedicoEspecialista {
        
        public IsrvMedicoEspecialistaClient() {
        }
        
        public IsrvMedicoEspecialistaClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public IsrvMedicoEspecialistaClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public IsrvMedicoEspecialistaClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public IsrvMedicoEspecialistaClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public System.Collections.Generic.List<Entidades.PA_MedicoEspecialista_MostrarDetalle_Result> recMedicoEspecialista_PA() {
            return base.Channel.recMedicoEspecialista_PA();
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.List<Entidades.PA_MedicoEspecialista_MostrarDetalle_Result>> recMedicoEspecialista_PAAsync() {
            return base.Channel.recMedicoEspecialista_PAAsync();
        }
        
        public Entidades.PA_MedicoEspecialista_MostrarDetallexid_Result recMedicoEspecialistaXID_PA(int id) {
            return base.Channel.recMedicoEspecialistaXID_PA(id);
        }
        
        public System.Threading.Tasks.Task<Entidades.PA_MedicoEspecialista_MostrarDetallexid_Result> recMedicoEspecialistaXID_PAAsync(int id) {
            return base.Channel.recMedicoEspecialistaXID_PAAsync(id);
        }
        
        public bool insMedicoEspecialista_PA(Entidades.MedicoEspecialista pMedicoEspecialista) {
            return base.Channel.insMedicoEspecialista_PA(pMedicoEspecialista);
        }
        
        public System.Threading.Tasks.Task<bool> insMedicoEspecialista_PAAsync(Entidades.MedicoEspecialista pMedicoEspecialista) {
            return base.Channel.insMedicoEspecialista_PAAsync(pMedicoEspecialista);
        }
        
        public bool modMedicoEspecialista_PA(Entidades.MedicoEspecialista pMedicoEspecialista) {
            return base.Channel.modMedicoEspecialista_PA(pMedicoEspecialista);
        }
        
        public System.Threading.Tasks.Task<bool> modMedicoEspecialista_PAAsync(Entidades.MedicoEspecialista pMedicoEspecialista) {
            return base.Channel.modMedicoEspecialista_PAAsync(pMedicoEspecialista);
        }
        
        public bool delMedicoEspecialista_PA(Entidades.MedicoEspecialista pMedicoEspecialista) {
            return base.Channel.delMedicoEspecialista_PA(pMedicoEspecialista);
        }
        
        public System.Threading.Tasks.Task<bool> delMedicoEspecialista_PAAsync(Entidades.MedicoEspecialista pMedicoEspecialista) {
            return base.Channel.delMedicoEspecialista_PAAsync(pMedicoEspecialista);
        }
    }
}
