//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hospital_ABC.srvPacientes {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="srvPacientes.IsrvPacientes")]
    public interface IsrvPacientes {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IsrvPacientes/recPacientes_PA", ReplyAction="http://tempuri.org/IsrvPacientes/recPacientes_PAResponse")]
        System.Collections.Generic.List<Entidades.PA_Pacientes_MostrarDetalle_Result> recPacientes_PA();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IsrvPacientes/recPacientes_PA", ReplyAction="http://tempuri.org/IsrvPacientes/recPacientes_PAResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.List<Entidades.PA_Pacientes_MostrarDetalle_Result>> recPacientes_PAAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IsrvPacientes/recPacientesXID_PA", ReplyAction="http://tempuri.org/IsrvPacientes/recPacientesXID_PAResponse")]
        Entidades.PA_Pacientes_MostrarDetallexid_Result recPacientesXID_PA(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IsrvPacientes/recPacientesXID_PA", ReplyAction="http://tempuri.org/IsrvPacientes/recPacientesXID_PAResponse")]
        System.Threading.Tasks.Task<Entidades.PA_Pacientes_MostrarDetallexid_Result> recPacientesXID_PAAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IsrvPacientes/insPacientes_PA", ReplyAction="http://tempuri.org/IsrvPacientes/insPacientes_PAResponse")]
        bool insPacientes_PA(Entidades.Paciente pPaciente);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IsrvPacientes/insPacientes_PA", ReplyAction="http://tempuri.org/IsrvPacientes/insPacientes_PAResponse")]
        System.Threading.Tasks.Task<bool> insPacientes_PAAsync(Entidades.Paciente pPaciente);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IsrvPacientes/modPacientes_PA", ReplyAction="http://tempuri.org/IsrvPacientes/modPacientes_PAResponse")]
        bool modPacientes_PA(Entidades.Paciente pPaciente);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IsrvPacientes/modPacientes_PA", ReplyAction="http://tempuri.org/IsrvPacientes/modPacientes_PAResponse")]
        System.Threading.Tasks.Task<bool> modPacientes_PAAsync(Entidades.Paciente pPaciente);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IsrvPacientes/delPacientes_PA", ReplyAction="http://tempuri.org/IsrvPacientes/delPacientes_PAResponse")]
        bool delPacientes_PA(Entidades.Paciente pPaciente);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IsrvPacientes/delPacientes_PA", ReplyAction="http://tempuri.org/IsrvPacientes/delPacientes_PAResponse")]
        System.Threading.Tasks.Task<bool> delPacientes_PAAsync(Entidades.Paciente pPaciente);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IsrvPacientesChannel : Hospital_ABC.srvPacientes.IsrvPacientes, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class IsrvPacientesClient : System.ServiceModel.ClientBase<Hospital_ABC.srvPacientes.IsrvPacientes>, Hospital_ABC.srvPacientes.IsrvPacientes {
        
        public IsrvPacientesClient() {
        }
        
        public IsrvPacientesClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public IsrvPacientesClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public IsrvPacientesClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public IsrvPacientesClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public System.Collections.Generic.List<Entidades.PA_Pacientes_MostrarDetalle_Result> recPacientes_PA() {
            return base.Channel.recPacientes_PA();
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.List<Entidades.PA_Pacientes_MostrarDetalle_Result>> recPacientes_PAAsync() {
            return base.Channel.recPacientes_PAAsync();
        }
        
        public Entidades.PA_Pacientes_MostrarDetallexid_Result recPacientesXID_PA(int id) {
            return base.Channel.recPacientesXID_PA(id);
        }
        
        public System.Threading.Tasks.Task<Entidades.PA_Pacientes_MostrarDetallexid_Result> recPacientesXID_PAAsync(int id) {
            return base.Channel.recPacientesXID_PAAsync(id);
        }
        
        public bool insPacientes_PA(Entidades.Paciente pPaciente) {
            return base.Channel.insPacientes_PA(pPaciente);
        }
        
        public System.Threading.Tasks.Task<bool> insPacientes_PAAsync(Entidades.Paciente pPaciente) {
            return base.Channel.insPacientes_PAAsync(pPaciente);
        }
        
        public bool modPacientes_PA(Entidades.Paciente pPaciente) {
            return base.Channel.modPacientes_PA(pPaciente);
        }
        
        public System.Threading.Tasks.Task<bool> modPacientes_PAAsync(Entidades.Paciente pPaciente) {
            return base.Channel.modPacientes_PAAsync(pPaciente);
        }
        
        public bool delPacientes_PA(Entidades.Paciente pPaciente) {
            return base.Channel.delPacientes_PA(pPaciente);
        }
        
        public System.Threading.Tasks.Task<bool> delPacientes_PAAsync(Entidades.Paciente pPaciente) {
            return base.Channel.delPacientes_PAAsync(pPaciente);
        }
    }
}
