//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hospital_ABC.srvMedicamento {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="srvMedicamento.IsrvMedicamento")]
    public interface IsrvMedicamento {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IsrvMedicamento/recMedicamentos_PA", ReplyAction="http://tempuri.org/IsrvMedicamento/recMedicamentos_PAResponse")]
        System.Collections.Generic.List<Entidades.PA_Medicamentos_MostrarDetalle_Result> recMedicamentos_PA();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IsrvMedicamento/recMedicamentos_PA", ReplyAction="http://tempuri.org/IsrvMedicamento/recMedicamentos_PAResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.List<Entidades.PA_Medicamentos_MostrarDetalle_Result>> recMedicamentos_PAAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IsrvMedicamento/recMedicamentosXID_PA", ReplyAction="http://tempuri.org/IsrvMedicamento/recMedicamentosXID_PAResponse")]
        Entidades.PA_Medicamentos_MostrarDetallexid_Result recMedicamentosXID_PA(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IsrvMedicamento/recMedicamentosXID_PA", ReplyAction="http://tempuri.org/IsrvMedicamento/recMedicamentosXID_PAResponse")]
        System.Threading.Tasks.Task<Entidades.PA_Medicamentos_MostrarDetallexid_Result> recMedicamentosXID_PAAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IsrvMedicamento/insMedicamentos_PA", ReplyAction="http://tempuri.org/IsrvMedicamento/insMedicamentos_PAResponse")]
        bool insMedicamentos_PA(Entidades.Medicamento pMedicamentos);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IsrvMedicamento/insMedicamentos_PA", ReplyAction="http://tempuri.org/IsrvMedicamento/insMedicamentos_PAResponse")]
        System.Threading.Tasks.Task<bool> insMedicamentos_PAAsync(Entidades.Medicamento pMedicamentos);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IsrvMedicamento/modMedicamentos_PA", ReplyAction="http://tempuri.org/IsrvMedicamento/modMedicamentos_PAResponse")]
        bool modMedicamentos_PA(Entidades.Medicamento pMedicamentos);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IsrvMedicamento/modMedicamentos_PA", ReplyAction="http://tempuri.org/IsrvMedicamento/modMedicamentos_PAResponse")]
        System.Threading.Tasks.Task<bool> modMedicamentos_PAAsync(Entidades.Medicamento pMedicamentos);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IsrvMedicamento/delMedicamentos_PA", ReplyAction="http://tempuri.org/IsrvMedicamento/delMedicamentos_PAResponse")]
        bool delMedicamentos_PA(Entidades.Medicamento pMedicamentos);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IsrvMedicamento/delMedicamentos_PA", ReplyAction="http://tempuri.org/IsrvMedicamento/delMedicamentos_PAResponse")]
        System.Threading.Tasks.Task<bool> delMedicamentos_PAAsync(Entidades.Medicamento pMedicamentos);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IsrvMedicamentoChannel : Hospital_ABC.srvMedicamento.IsrvMedicamento, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class IsrvMedicamentoClient : System.ServiceModel.ClientBase<Hospital_ABC.srvMedicamento.IsrvMedicamento>, Hospital_ABC.srvMedicamento.IsrvMedicamento {
        
        public IsrvMedicamentoClient() {
        }
        
        public IsrvMedicamentoClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public IsrvMedicamentoClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public IsrvMedicamentoClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public IsrvMedicamentoClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public System.Collections.Generic.List<Entidades.PA_Medicamentos_MostrarDetalle_Result> recMedicamentos_PA() {
            return base.Channel.recMedicamentos_PA();
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.List<Entidades.PA_Medicamentos_MostrarDetalle_Result>> recMedicamentos_PAAsync() {
            return base.Channel.recMedicamentos_PAAsync();
        }
        
        public Entidades.PA_Medicamentos_MostrarDetallexid_Result recMedicamentosXID_PA(int id) {
            return base.Channel.recMedicamentosXID_PA(id);
        }
        
        public System.Threading.Tasks.Task<Entidades.PA_Medicamentos_MostrarDetallexid_Result> recMedicamentosXID_PAAsync(int id) {
            return base.Channel.recMedicamentosXID_PAAsync(id);
        }
        
        public bool insMedicamentos_PA(Entidades.Medicamento pMedicamentos) {
            return base.Channel.insMedicamentos_PA(pMedicamentos);
        }
        
        public System.Threading.Tasks.Task<bool> insMedicamentos_PAAsync(Entidades.Medicamento pMedicamentos) {
            return base.Channel.insMedicamentos_PAAsync(pMedicamentos);
        }
        
        public bool modMedicamentos_PA(Entidades.Medicamento pMedicamentos) {
            return base.Channel.modMedicamentos_PA(pMedicamentos);
        }
        
        public System.Threading.Tasks.Task<bool> modMedicamentos_PAAsync(Entidades.Medicamento pMedicamentos) {
            return base.Channel.modMedicamentos_PAAsync(pMedicamentos);
        }
        
        public bool delMedicamentos_PA(Entidades.Medicamento pMedicamentos) {
            return base.Channel.delMedicamentos_PA(pMedicamentos);
        }
        
        public System.Threading.Tasks.Task<bool> delMedicamentos_PAAsync(Entidades.Medicamento pMedicamentos) {
            return base.Channel.delMedicamentos_PAAsync(pMedicamentos);
        }
    }
}
