//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hospital_ABC.srvRegistroCitas {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="srvRegistroCitas.IsrvRegistroCitas")]
    public interface IsrvRegistroCitas {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IsrvRegistroCitas/recRegistroCitas_PA", ReplyAction="http://tempuri.org/IsrvRegistroCitas/recRegistroCitas_PAResponse")]
        System.Collections.Generic.List<Entidades.PA_RegistroCitas_MostrarDetalle_Result> recRegistroCitas_PA();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IsrvRegistroCitas/recRegistroCitas_PA", ReplyAction="http://tempuri.org/IsrvRegistroCitas/recRegistroCitas_PAResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.List<Entidades.PA_RegistroCitas_MostrarDetalle_Result>> recRegistroCitas_PAAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IsrvRegistroCitas/recRegistroCitasXID_PA", ReplyAction="http://tempuri.org/IsrvRegistroCitas/recRegistroCitasXID_PAResponse")]
        Entidades.PA_RegistroCitas_MostrarDetallexid_Result recRegistroCitasXID_PA(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IsrvRegistroCitas/recRegistroCitasXID_PA", ReplyAction="http://tempuri.org/IsrvRegistroCitas/recRegistroCitasXID_PAResponse")]
        System.Threading.Tasks.Task<Entidades.PA_RegistroCitas_MostrarDetallexid_Result> recRegistroCitasXID_PAAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IsrvRegistroCitas/insRegistroCitas_PA", ReplyAction="http://tempuri.org/IsrvRegistroCitas/insRegistroCitas_PAResponse")]
        bool insRegistroCitas_PA(Entidades.RegistroCitas pRegistroCitas);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IsrvRegistroCitas/insRegistroCitas_PA", ReplyAction="http://tempuri.org/IsrvRegistroCitas/insRegistroCitas_PAResponse")]
        System.Threading.Tasks.Task<bool> insRegistroCitas_PAAsync(Entidades.RegistroCitas pRegistroCitas);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IsrvRegistroCitas/modRegistroCitas_PA", ReplyAction="http://tempuri.org/IsrvRegistroCitas/modRegistroCitas_PAResponse")]
        bool modRegistroCitas_PA(Entidades.RegistroCitas pRegistroCitas);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IsrvRegistroCitas/modRegistroCitas_PA", ReplyAction="http://tempuri.org/IsrvRegistroCitas/modRegistroCitas_PAResponse")]
        System.Threading.Tasks.Task<bool> modRegistroCitas_PAAsync(Entidades.RegistroCitas pRegistroCitas);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IsrvRegistroCitas/delRegistroCitas_PA", ReplyAction="http://tempuri.org/IsrvRegistroCitas/delRegistroCitas_PAResponse")]
        bool delRegistroCitas_PA(Entidades.RegistroCitas pRegistroCitas);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IsrvRegistroCitas/delRegistroCitas_PA", ReplyAction="http://tempuri.org/IsrvRegistroCitas/delRegistroCitas_PAResponse")]
        System.Threading.Tasks.Task<bool> delRegistroCitas_PAAsync(Entidades.RegistroCitas pRegistroCitas);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IsrvRegistroCitasChannel : Hospital_ABC.srvRegistroCitas.IsrvRegistroCitas, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class IsrvRegistroCitasClient : System.ServiceModel.ClientBase<Hospital_ABC.srvRegistroCitas.IsrvRegistroCitas>, Hospital_ABC.srvRegistroCitas.IsrvRegistroCitas {
        
        public IsrvRegistroCitasClient() {
        }
        
        public IsrvRegistroCitasClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public IsrvRegistroCitasClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public IsrvRegistroCitasClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public IsrvRegistroCitasClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public System.Collections.Generic.List<Entidades.PA_RegistroCitas_MostrarDetalle_Result> recRegistroCitas_PA() {
            return base.Channel.recRegistroCitas_PA();
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.List<Entidades.PA_RegistroCitas_MostrarDetalle_Result>> recRegistroCitas_PAAsync() {
            return base.Channel.recRegistroCitas_PAAsync();
        }
        
        public Entidades.PA_RegistroCitas_MostrarDetallexid_Result recRegistroCitasXID_PA(int id) {
            return base.Channel.recRegistroCitasXID_PA(id);
        }
        
        public System.Threading.Tasks.Task<Entidades.PA_RegistroCitas_MostrarDetallexid_Result> recRegistroCitasXID_PAAsync(int id) {
            return base.Channel.recRegistroCitasXID_PAAsync(id);
        }
        
        public bool insRegistroCitas_PA(Entidades.RegistroCitas pRegistroCitas) {
            return base.Channel.insRegistroCitas_PA(pRegistroCitas);
        }
        
        public System.Threading.Tasks.Task<bool> insRegistroCitas_PAAsync(Entidades.RegistroCitas pRegistroCitas) {
            return base.Channel.insRegistroCitas_PAAsync(pRegistroCitas);
        }
        
        public bool modRegistroCitas_PA(Entidades.RegistroCitas pRegistroCitas) {
            return base.Channel.modRegistroCitas_PA(pRegistroCitas);
        }
        
        public System.Threading.Tasks.Task<bool> modRegistroCitas_PAAsync(Entidades.RegistroCitas pRegistroCitas) {
            return base.Channel.modRegistroCitas_PAAsync(pRegistroCitas);
        }
        
        public bool delRegistroCitas_PA(Entidades.RegistroCitas pRegistroCitas) {
            return base.Channel.delRegistroCitas_PA(pRegistroCitas);
        }
        
        public System.Threading.Tasks.Task<bool> delRegistroCitas_PAAsync(Entidades.RegistroCitas pRegistroCitas) {
            return base.Channel.delRegistroCitas_PAAsync(pRegistroCitas);
        }
    }
}
