//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hospital_ABC.srvEspecialidad {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="srvEspecialidad.IsrvEspecialidad")]
    public interface IsrvEspecialidad {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IsrvEspecialidad/recEspecialidad_PA", ReplyAction="http://tempuri.org/IsrvEspecialidad/recEspecialidad_PAResponse")]
        System.Collections.Generic.List<Entidades.PA_Especialidad_MostrarDetalle_Result> recEspecialidad_PA();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IsrvEspecialidad/recEspecialidad_PA", ReplyAction="http://tempuri.org/IsrvEspecialidad/recEspecialidad_PAResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.List<Entidades.PA_Especialidad_MostrarDetalle_Result>> recEspecialidad_PAAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IsrvEspecialidad/recEspecialidadXID_PA", ReplyAction="http://tempuri.org/IsrvEspecialidad/recEspecialidadXID_PAResponse")]
        Entidades.PA_Especialidad_MostrarDetallexid_Result recEspecialidadXID_PA(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IsrvEspecialidad/recEspecialidadXID_PA", ReplyAction="http://tempuri.org/IsrvEspecialidad/recEspecialidadXID_PAResponse")]
        System.Threading.Tasks.Task<Entidades.PA_Especialidad_MostrarDetallexid_Result> recEspecialidadXID_PAAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IsrvEspecialidad/insEspecialidad_PA", ReplyAction="http://tempuri.org/IsrvEspecialidad/insEspecialidad_PAResponse")]
        bool insEspecialidad_PA(Entidades.Especialidades pEspecialidad);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IsrvEspecialidad/insEspecialidad_PA", ReplyAction="http://tempuri.org/IsrvEspecialidad/insEspecialidad_PAResponse")]
        System.Threading.Tasks.Task<bool> insEspecialidad_PAAsync(Entidades.Especialidades pEspecialidad);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IsrvEspecialidad/modEspecialidad_PA", ReplyAction="http://tempuri.org/IsrvEspecialidad/modEspecialidad_PAResponse")]
        bool modEspecialidad_PA(Entidades.Especialidades pEspecialidad);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IsrvEspecialidad/modEspecialidad_PA", ReplyAction="http://tempuri.org/IsrvEspecialidad/modEspecialidad_PAResponse")]
        System.Threading.Tasks.Task<bool> modEspecialidad_PAAsync(Entidades.Especialidades pEspecialidad);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IsrvEspecialidad/delEspecialidad_PA", ReplyAction="http://tempuri.org/IsrvEspecialidad/delEspecialidad_PAResponse")]
        bool delEspecialidad_PA(Entidades.Especialidades pEspecialidad);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IsrvEspecialidad/delEspecialidad_PA", ReplyAction="http://tempuri.org/IsrvEspecialidad/delEspecialidad_PAResponse")]
        System.Threading.Tasks.Task<bool> delEspecialidad_PAAsync(Entidades.Especialidades pEspecialidad);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IsrvEspecialidadChannel : Hospital_ABC.srvEspecialidad.IsrvEspecialidad, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class IsrvEspecialidadClient : System.ServiceModel.ClientBase<Hospital_ABC.srvEspecialidad.IsrvEspecialidad>, Hospital_ABC.srvEspecialidad.IsrvEspecialidad {
        
        public IsrvEspecialidadClient() {
        }
        
        public IsrvEspecialidadClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public IsrvEspecialidadClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public IsrvEspecialidadClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public IsrvEspecialidadClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public System.Collections.Generic.List<Entidades.PA_Especialidad_MostrarDetalle_Result> recEspecialidad_PA() {
            return base.Channel.recEspecialidad_PA();
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.List<Entidades.PA_Especialidad_MostrarDetalle_Result>> recEspecialidad_PAAsync() {
            return base.Channel.recEspecialidad_PAAsync();
        }
        
        public Entidades.PA_Especialidad_MostrarDetallexid_Result recEspecialidadXID_PA(int id) {
            return base.Channel.recEspecialidadXID_PA(id);
        }
        
        public System.Threading.Tasks.Task<Entidades.PA_Especialidad_MostrarDetallexid_Result> recEspecialidadXID_PAAsync(int id) {
            return base.Channel.recEspecialidadXID_PAAsync(id);
        }
        
        public bool insEspecialidad_PA(Entidades.Especialidades pEspecialidad) {
            return base.Channel.insEspecialidad_PA(pEspecialidad);
        }
        
        public System.Threading.Tasks.Task<bool> insEspecialidad_PAAsync(Entidades.Especialidades pEspecialidad) {
            return base.Channel.insEspecialidad_PAAsync(pEspecialidad);
        }
        
        public bool modEspecialidad_PA(Entidades.Especialidades pEspecialidad) {
            return base.Channel.modEspecialidad_PA(pEspecialidad);
        }
        
        public System.Threading.Tasks.Task<bool> modEspecialidad_PAAsync(Entidades.Especialidades pEspecialidad) {
            return base.Channel.modEspecialidad_PAAsync(pEspecialidad);
        }
        
        public bool delEspecialidad_PA(Entidades.Especialidades pEspecialidad) {
            return base.Channel.delEspecialidad_PA(pEspecialidad);
        }
        
        public System.Threading.Tasks.Task<bool> delEspecialidad_PAAsync(Entidades.Especialidades pEspecialidad) {
            return base.Channel.delEspecialidad_PAAsync(pEspecialidad);
        }
    }
}
