//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hospital_ABC.srvDiagnostico {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="srvDiagnostico.IsrvDiagnostico")]
    public interface IsrvDiagnostico {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IsrvDiagnostico/recDiagnostico_PA", ReplyAction="http://tempuri.org/IsrvDiagnostico/recDiagnostico_PAResponse")]
        System.Collections.Generic.List<Entidades.PA_Diagnostico_MostrarDetalle_Result> recDiagnostico_PA();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IsrvDiagnostico/recDiagnostico_PA", ReplyAction="http://tempuri.org/IsrvDiagnostico/recDiagnostico_PAResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.List<Entidades.PA_Diagnostico_MostrarDetalle_Result>> recDiagnostico_PAAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IsrvDiagnostico/recDiagnosticoXID_PA", ReplyAction="http://tempuri.org/IsrvDiagnostico/recDiagnosticoXID_PAResponse")]
        Entidades.PA_Diagnostico_MostrarDetallexid_Result recDiagnosticoXID_PA(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IsrvDiagnostico/recDiagnosticoXID_PA", ReplyAction="http://tempuri.org/IsrvDiagnostico/recDiagnosticoXID_PAResponse")]
        System.Threading.Tasks.Task<Entidades.PA_Diagnostico_MostrarDetallexid_Result> recDiagnosticoXID_PAAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IsrvDiagnostico/insDiagnostico_PA", ReplyAction="http://tempuri.org/IsrvDiagnostico/insDiagnostico_PAResponse")]
        bool insDiagnostico_PA(Entidades.Diagnostico pDiagnostico);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IsrvDiagnostico/insDiagnostico_PA", ReplyAction="http://tempuri.org/IsrvDiagnostico/insDiagnostico_PAResponse")]
        System.Threading.Tasks.Task<bool> insDiagnostico_PAAsync(Entidades.Diagnostico pDiagnostico);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IsrvDiagnostico/modDiagnostico_PA", ReplyAction="http://tempuri.org/IsrvDiagnostico/modDiagnostico_PAResponse")]
        bool modDiagnostico_PA(Entidades.Diagnostico pDiagnostico);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IsrvDiagnostico/modDiagnostico_PA", ReplyAction="http://tempuri.org/IsrvDiagnostico/modDiagnostico_PAResponse")]
        System.Threading.Tasks.Task<bool> modDiagnostico_PAAsync(Entidades.Diagnostico pDiagnostico);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IsrvDiagnostico/delDiagnostico_PA", ReplyAction="http://tempuri.org/IsrvDiagnostico/delDiagnostico_PAResponse")]
        bool delDiagnostico_PA(Entidades.Diagnostico pDiagnostico);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IsrvDiagnostico/delDiagnostico_PA", ReplyAction="http://tempuri.org/IsrvDiagnostico/delDiagnostico_PAResponse")]
        System.Threading.Tasks.Task<bool> delDiagnostico_PAAsync(Entidades.Diagnostico pDiagnostico);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IsrvDiagnosticoChannel : Hospital_ABC.srvDiagnostico.IsrvDiagnostico, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class IsrvDiagnosticoClient : System.ServiceModel.ClientBase<Hospital_ABC.srvDiagnostico.IsrvDiagnostico>, Hospital_ABC.srvDiagnostico.IsrvDiagnostico {
        
        public IsrvDiagnosticoClient() {
        }
        
        public IsrvDiagnosticoClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public IsrvDiagnosticoClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public IsrvDiagnosticoClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public IsrvDiagnosticoClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public System.Collections.Generic.List<Entidades.PA_Diagnostico_MostrarDetalle_Result> recDiagnostico_PA() {
            return base.Channel.recDiagnostico_PA();
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.List<Entidades.PA_Diagnostico_MostrarDetalle_Result>> recDiagnostico_PAAsync() {
            return base.Channel.recDiagnostico_PAAsync();
        }
        
        public Entidades.PA_Diagnostico_MostrarDetallexid_Result recDiagnosticoXID_PA(int id) {
            return base.Channel.recDiagnosticoXID_PA(id);
        }
        
        public System.Threading.Tasks.Task<Entidades.PA_Diagnostico_MostrarDetallexid_Result> recDiagnosticoXID_PAAsync(int id) {
            return base.Channel.recDiagnosticoXID_PAAsync(id);
        }
        
        public bool insDiagnostico_PA(Entidades.Diagnostico pDiagnostico) {
            return base.Channel.insDiagnostico_PA(pDiagnostico);
        }
        
        public System.Threading.Tasks.Task<bool> insDiagnostico_PAAsync(Entidades.Diagnostico pDiagnostico) {
            return base.Channel.insDiagnostico_PAAsync(pDiagnostico);
        }
        
        public bool modDiagnostico_PA(Entidades.Diagnostico pDiagnostico) {
            return base.Channel.modDiagnostico_PA(pDiagnostico);
        }
        
        public System.Threading.Tasks.Task<bool> modDiagnostico_PAAsync(Entidades.Diagnostico pDiagnostico) {
            return base.Channel.modDiagnostico_PAAsync(pDiagnostico);
        }
        
        public bool delDiagnostico_PA(Entidades.Diagnostico pDiagnostico) {
            return base.Channel.delDiagnostico_PA(pDiagnostico);
        }
        
        public System.Threading.Tasks.Task<bool> delDiagnostico_PAAsync(Entidades.Diagnostico pDiagnostico) {
            return base.Channel.delDiagnostico_PAAsync(pDiagnostico);
        }
    }
}
